version: "3.7"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/plex:/config
      - /data/media:/data/media
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/radarr:/config
      - /data/media:/data/media
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/sonarr:/config
      - /data/media:/data/media
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
  jackett:
    container_name: jackett
    image: cr.hotio.dev/hotio/jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/jackett:/config
      - /data/media:/data/media
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /data/media/sdb/torrents:/data/media/torrents
  sonarr-anime:
    container_name: sonarr-anime
    image: cr.hotio.dev/hotio/sonarr
    ports:
      - 8888:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/sonarr-anime:/config
      - /data/media:/data/media
  radarr-4k:
    container_name: radarr-4k
    image: cr.hotio.dev/hotio/radarr
    ports:
      - 7777:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/radarr-4k:/config
      - /data/media:/data/media
