version: "3.7"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
      - PLEX_CLAIM=claim-zaXzBKyEwtcYr811vwtR
    volumes:
      - /docker/appdata/plex:/config
      - /data/media:/data/media
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/radarr:/config
      - /data:/data
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/sonarr:/config
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/bazarr:/config
  jackett:
    container_name: jackett
    image: cr.hotio.dev/hotio/jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/jackett:/config
      - /data/jackett:/data/jackett
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      - UMASK=000
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /app/qBittorrent/downloads:/data/torrents